### ISSUE TITLE
Channel keeps getting set to invite only.

### ISSUE THREAD

**Issue by chirayudesai** [Gnuxie/Draupnir#72]
We deploy Draupnir through [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy), migrated from a previous install of Mjolnir.

Current version: v1.83.0

One of the protected channels (and only one) keeps getting set to private from time to time.

Example event:

```
{
  "content": {
    "join_rule": "invite"
  },
  "origin_server_ts": 1692574292625,
  "room_id": "!aPqEsAdWuysydZNCic:matrix.org",
  "sender": "@nickcalyx:matrix.org",
  "state_key": "",
  "type": "m.room.join_rules",
  "unsigned": {
    "replaces_state": "$xbLTAhmv9EXBxYgs7w-zdAtEfI2fU9bq1iIX3zQqw-A",
    "prev_content": {
      "join_rule": "invite"
    },
    "prev_sender": "@bot.mjolnir:calyx.dev",
    "age": 45597433
  },
  "event_id": "$YGWMm0WXP3-aV11wMP9egt6Z2Ww9Q6egaIQYqXk4Y-I",
  "user_id": "@nickcalyx:matrix.org",
  "age": 45597433,
  "replaces_state": "$xbLTAhmv9EXBxYgs7w-zdAtEfI2fU9bq1iIX3zQqw-A",
  "prev_content": {
    "join_rule": "invite"
  }
}
```

The thing to note here is `prev_sender` and `prev_content`, where it shows the bot setting the channel as invite only.

We've set it to public again after this, but from time to time we find that it gets set to private, and we see a similar event like the above.

The `JoinWaveShortCircuit` protection has been disabled for a while. It was briefly enabled a long time ago. Mentioned because that's the only place in the code here where I see join_rules being touched.

**Comment by chirayudesai** [comment]
The room this happens to is `#CalyxOS:matrix.org` - there's a bunch more protected rooms which are fine, and I don't remember for sure but they most likely didn't ever got hit by a `JoinWave` either.

**Comment by Gnuxie** [comment]
As discussed in https://matrix.to/#/!IaWNErZAgQUhGqJXjX:matrix.org/$h1Bjtqm7w4FsnDESOOAREFqI-uhkfu5mG6t75wFxhyE?via=matrix.org&via=the-apothecary.club&via=envs.net. Given the room's, version (6), age (+2years) and size (8k~) it's likely caused by a state reset/resolution issue.
[timeline.txt](https://github.com/Gnuxie/Draupnir/files/12408272/timeline.txt). There also seems to only be one event issued by the draupnir/mjolnir account and that was two months ago. 

I would recommend upgrading the room as there may be other issues silently going unnoticed. As the problem has been discovered by noticing the join rule changing, then some of the ongoing effects could be pretty dramatic. Theoretically  there could be servers participating in the room but never having their users messages reach anyone else.

If you need any assistance/questions with upgrading then you are welcome to ask in #draupnir:matrix.org again, though there are probably other support channels better suited. I'm sorry that this has happened to your room.

**Comment by chirayudesai** [comment]
Thanks so much for looking into this!
